/**
 * CHASM OF THE PLENUM - SYSTEM CONFIGURATION & IMPROVEMENT REGISTRY
 * 
 * Based on the 5 Foundational Axioms:
 * 1. Environment: 32-Hour Subterranean Brine Tide (The Plenum-Rise)
 * 2. Biology: Costal Gill-Cleft & Silica Toxicity (Dual Respiration & Vitrification)
 * 3. Resources: Vitreous Silic-Timber & Corrosive Mist (Borosilicate Wood & Basalt)
 * 4. Movement: Gravity Funiculars & The Hydro-Gradient (Catenary Cableways & Water Hoists)
 * 5. Social Organization: The Wash-Compact & The Hydrological Ledger (Reciprocal Altitude Barter)
 */

export const AXIOMS = {
  ENVIRONMENT: {
    TIDE_HOURS: 32,
    RISE_HOURS: 14,
    SLACK_1_HOURS: 2,
    EBB_HOURS: 14,
    SLACK_2_HOURS: 2,
    MAX_FLOOD_DEPTH_M: 60,
    MIST_CONTOUR_MAX_M: 700,
    SCARP_ALTITUDE_M: 1400,
    SHELF_ALTITUDE_M: 700,
    GUT_ALTITUDE_M: 50,
    LOWLAND_TEMP_C: 42,
    HIGHLAND_TEMP_C: -8
  },
  BIOLOGY: {
    PLEAT_PAIRS: 6,
    MAX_SILICA_HOURS: 12,
    HOLLOW_WASTING_HOURS: 96,
    CLEAN_RINSE_VOLUME_L: 12,
    CHOKE_VALVE_DEFAULT_MM: 12,
    CHOKE_VALVE_PENALTY_MM: 4
  },
  RESOURCES: {
    SILIC_TIMBER_FREQUENCY_HZ: 4200,
    ACID_LYE_STRENGTH: 0.85,
    BASALT_DENSITY_KG_M3: 3000
  },
  MOVEMENT: {
    HOIST_WATER_BALLAST_L: 10000,
    HOIST_PAYLOAD_KG: 8000,
    CABLE_MAX_TENSION_KG: 80000,
    FUNICULAR_DROP_M: 650
  },
  ECONOMY: {
    BASE_LEK_LITER: 1.12,
    CRISIS_PEAK_LEK: 4.80,
    KELP_FLOUR_BASE: 3.20,
    MANNA_CURD_BASE: 0.80,
    SILIC_PINS_BASE: 0.45,
    VINEGAR_LYE_BASE: 1.50,
    SALT_BEEF_BASE: 5.00
  }
};

export const TIDE_STROKES = [
  { id: 'gush', name: 'Gush', startHour: 0, endHour: 4, desc: 'Subterranean brine expansion; lowlands inundate; Scour updrafts' },
  { id: 'steam', name: 'Steam', startHour: 4, endHour: 14, desc: 'High Plenum fog immersion; boiling gut submerged; gill breathing' },
  { id: 'drain', name: 'Drain', startHour: 14, endHour: 18, desc: 'Ebb cascades into karst chimneys; Throat-Sink downdrafts; funicular drop' },
  { id: 'silt', name: 'Silt', startHour: 18, endHour: 32, desc: 'Dry desiccation; freezing plateau winds; mud scraping & cable transit' }
];

export const NPCS = [
  { id: 'vaelen', name: 'Vaelen Keth', role: 'High Warden of the Pipe', tier: 'Scarp', health: 'Clear-Flank', waterScrip: 450 },
  { id: 'kallum', name: 'Kallum of Wharf 9', role: 'Bailiff of the Low Basket', tier: 'Gut', health: 'Chalk-Ribs', waterScrip: 85 },
  { id: 'barek', name: 'Barek of the Sheave', role: 'Master Cable-Tender', tier: 'Shelf', health: 'Clear-Flank', waterScrip: 140 },
  { id: 'morwen', name: 'Sister Morwen', role: 'Cistern Prioress', tier: 'Scarp', health: 'Wax-Sealed', waterScrip: 600 },
  { id: 'elyse', name: 'Doctor Elyse', role: 'Master Pleat-Leech', tier: 'Shelf', health: 'Clear-Flank', waterScrip: 210 },
  { id: 'caelen', name: 'Old Caelen', role: 'The Stone-Judge', tier: 'Shelf', health: 'Stone-Joints', waterScrip: 30 },
  { id: 'sola', name: 'Sola the Zip-Courier', role: 'Acoustic Courier', tier: 'Shelf', health: 'Clear-Flank', waterScrip: 95 },
  { id: 'thura', name: 'Mire-Mother Thura', role: 'Algal Matron', tier: 'Gut', health: 'Chalk-Ribs', waterScrip: 180 },
  { id: 'garrick', name: 'Garrick the Broker', role: 'Valve-Bourse Speculator', tier: 'Shelf', health: 'Clear-Flank', waterScrip: 320 },
  { id: 'bran', name: 'Bran the Diver', role: 'Brine Scavenger', tier: 'Gut', health: 'Chalk-Ribs', waterScrip: 65 },
  { id: 'dun', name: 'Master Dun', role: 'Acoustic Gong-Tuner', tier: 'Shelf', health: 'Stone-Joints', waterScrip: 110 },
  { id: 'drusilla', name: 'Drusilla', role: 'Slug-Curd Farmer', tier: 'Shelf', health: 'Clear-Flank', waterScrip: 135 },
  { id: 'kaelen', name: 'Apprentice Kaelen', role: 'Junior Rigger', tier: 'Shelf', health: 'Clear-Flank', waterScrip: 40 },
  { id: 'jarek', name: 'Jarek the Drum-Driver', role: 'Funicular Hoistman', tier: 'Shelf', health: 'Chalk-Ribs', waterScrip: 155 },
  { id: 'nesta', name: 'Nesta', role: 'Shackle-Breaker (Saboteur)', tier: 'Gut', health: 'Chalk-Ribs', waterScrip: 20 },
  { id: 'talia', name: 'Talia the Scribe', role: 'Ledger Bookkeeper', tier: 'Scarp', health: 'Clear-Flank', waterScrip: 190 },
  { id: 'teth', name: 'Teth the Hauler', role: 'Mud-Sledge Laborer', tier: 'Gut', health: 'Chalk-Ribs (Severe)', waterScrip: 12 },
  { id: 'sari', name: 'Sari', role: 'Tavern Keeper (The Snapped Cable)', tier: 'Shelf', health: 'Clear-Flank', waterScrip: 220 },
  { id: 'varek', name: 'Varek', role: 'Water-Poacher', tier: 'Shelf', health: 'Chalk-Ribs', waterScrip: 45 },
  { id: 'orin', name: 'Orin the Engineer', role: 'Capillary Siphon Inventor', tier: 'Shelf', health: 'Clear-Flank', waterScrip: 175 }
];

export const IMPROVEMENTS = [
  // UIUX-01 to 50
  { id: 'UIUX-01', category: 'UIUX', name: 'Dynamic 32-hour Plenum Tide Clock HUD with 4 cyclic strokes' },
  { id: 'UIUX-02', category: 'UIUX', name: 'Real-time Costal Cleft Hydration and Vitrification status gauge' },
  { id: 'UIUX-03', category: 'UIUX', name: 'Barometric Altimeter HUD with altitude tier highlighting' },
  { id: 'UIUX-04', category: 'UIUX', name: 'Updraft and downdraft barometric wind vector indicator' },
  { id: 'UIUX-05', category: 'UIUX', name: 'Ambient sulfur and silica toxicity atmospheric meter' },
  { id: 'UIUX-06', category: 'UIUX', name: 'Tide-line safety proximity beacon alerting to rising brine' },
  { id: 'UIUX-07', category: 'UIUX', name: 'Condensation catchment rate meter for roof sluices' },
  { id: 'UIUX-08', category: 'UIUX', name: 'Hydrostatic municipal pipe pressure dial with blowout thresholds' },
  { id: 'UIUX-09', category: 'UIUX', name: 'Funicular descent velocity and brake-shoe temperature tachometer' },
  { id: 'UIUX-10', category: 'UIUX', name: 'Great Cistern reservoir capacity water-level float bars' },
  { id: 'UIUX-11', category: 'UIUX', name: 'Tactical 3D Chasm Minimap with altitude contour layer filtering' },
  { id: 'UIUX-12', category: 'UIUX', name: 'Vertical elevation cross-section HUD displaying human contour' },
  { id: 'UIUX-13', category: 'UIUX', name: 'Compass ribbon showing cardinal winds: The Scour and Throat-Sink' },
  { id: 'UIUX-14', category: 'UIUX', name: 'World-space 3D location beacon pins with distance alpha-falloff' },
  { id: 'UIUX-15', category: 'UIUX', name: 'Inhabitant POI status badges with physiological tier indicators' },
  { id: 'UIUX-16', category: 'UIUX', name: 'Siphon aqueduct laminar flow-vector overlays on pipe networks' },
  { id: 'UIUX-17', category: 'UIUX', name: 'Cableway mechanical tension stress heatmap overlay' },
  { id: 'UIUX-18', category: 'UIUX', name: 'Interactive cableway network transit map and terminal scheduler' },
  { id: 'UIUX-19', category: 'UIUX', name: 'Fog-penetrating acoustic sonar ping reticle with echo rings' },
  { id: 'UIUX-20', category: 'UIUX', name: 'Hazardous ledge boundary drop-off warning indicators' },
  { id: 'UIUX-21', category: 'UIUX', name: 'Live Siphon-Bourse commodity price ticker with real-time volatility' },
  { id: 'UIUX-22', category: 'UIUX', name: 'Water Scrip (Lek) digital wallet and transaction receipt ledger' },
  { id: 'UIUX-23', category: 'UIUX', name: 'Calcification mortgage calculator with daily water penalty readouts' },
  { id: 'UIUX-24', category: 'UIUX', name: 'Dual Diarchy decree viewer with Warden and Bailiff co-signatures' },
  { id: 'UIUX-25', category: 'UIUX', name: 'Trans-chasm trade throughput diagram with bottleneck nodes' },
  { id: 'UIUX-26', category: 'UIUX', name: 'Funicular freight queue and priority allocation inspector' },
  { id: 'UIUX-27', category: 'UIUX', name: 'Bakers Guild flour ration allotment board for the East Ledge' },
  { id: 'UIUX-28', category: 'UIUX', name: 'Sluice-Wharf Nine export tally board tracking kelp tonnage' },
  { id: 'UIUX-29', category: 'UIUX', name: 'Black-market water poaching risk meter with patrol awareness' },
  { id: 'UIUX-30', category: 'UIUX', name: 'Diplomatic betrothal treaty status widget (Lucan & Mira)' },
  { id: 'UIUX-31', category: 'UIUX', name: 'Inhabitant Dossier modal tracking 20 NPCs, schedules, and debts' },
  { id: 'UIUX-32', category: 'UIUX', name: 'World State Ledger live audit drawer comparing Pre vs Post disruption' },
  { id: 'UIUX-33', category: 'UIUX', name: 'Acoustic Resonance Spectrum analyzer with Hz readouts' },
  { id: 'UIUX-34', category: 'UIUX', name: 'Performance telemetry HUD tracking FPS, frame delta, and memory' },
  { id: 'UIUX-35', category: 'UIUX', name: 'Settings modal with persistent sliders for volume, FOV, and controls' },
  { id: 'UIUX-36', category: 'UIUX', name: 'Field manual viewer explaining the 5 foundational axioms' },
  { id: 'UIUX-37', category: 'UIUX', name: 'Director Photo Mode with rule-of-thirds grid and aperture settings' },
  { id: 'UIUX-38', category: 'UIUX', name: 'Audio mixer panel with separate category gains' },
  { id: 'UIUX-39', category: 'UIUX', name: 'Stacking toast notification manager with severity tinting' },
  { id: 'UIUX-40', category: 'UIUX', name: 'Crisis impact alert banner signaling bridge failure events' },
  { id: 'UIUX-41', category: 'UIUX', name: 'Full keyboard accessibility navigation with visible focus rings' },
  { id: 'UIUX-42', category: 'UIUX', name: 'ARIA live regions announcing tide stroke changes for screen readers' },
  { id: 'UIUX-43', category: 'UIUX', name: 'High-contrast palette toggle for enhanced daylight legibility' },
  { id: 'UIUX-44', category: 'UIUX', name: 'Reduced motion preference disabling head-bob and wind shakes' },
  { id: 'UIUX-45', category: 'UIUX', name: 'Mobile virtual joysticks and touch quick-dial action buttons' },
  { id: 'UIUX-46', category: 'UIUX', name: 'Responsive interface reflow down to 390px mobile viewports' },
  { id: 'UIUX-47', category: 'UIUX', name: 'Priority Escape key closure hierarchy for modals and menus' },
  { id: 'UIUX-48', category: 'UIUX', name: 'Screen-reader friendly metric card formatting with unit readouts' },
  { id: 'UIUX-49', category: 'UIUX', name: 'Dynamic contextual mouse cursor states (pointer, valve, grab, crosshair)' },
  { id: 'UIUX-50', category: 'UIUX', name: 'Instant coordinate and altitude copy-to-clipboard button' },

  // GAME-01 to 50
  { id: 'GAME-01', category: 'GAME', name: 'Seamless First-Person and Third-Person camera toggle' },
  { id: 'GAME-02', category: 'GAME', name: 'Sprint locomotion mechanics with stamina drain and recovery' },
  { id: 'GAME-03', category: 'GAME', name: 'Altitude-dependent gravity scaling between Scarp and Gut' },
  { id: 'GAME-04', category: 'GAME', name: 'Motion-coupled head-bob dynamically synced to locomotion speed' },
  { id: 'GAME-05', category: 'GAME', name: 'Surface-aware procedural footstep acoustics for basalt, wood, and silt' },
  { id: 'GAME-06', category: 'GAME', name: 'Fall damage simulation with updraft velocity deceleration' },
  { id: 'GAME-07', category: 'GAME', name: 'Mantle and ledge-grab physics on sheer cliff edges' },
  { id: 'GAME-08', category: 'GAME', name: 'Pumice-wood Mud-Stilts equipment for caustic silt navigation' },
  { id: 'GAME-09', category: 'GAME', name: 'Crouch stance for traversing narrow drainage flumes and flues' },
  { id: 'GAME-10', category: 'GAME', name: 'Scaffold and cliff-ladder climbing locomotion mechanics' },
  { id: 'GAME-11', category: 'GAME', name: 'Costal Cleft breathing mechanic absorbing mineral steam in Gut' },
  { id: 'GAME-12', category: 'GAME', name: 'Cleft vitrification progressive debuff causing joint stiffening' },
  { id: 'GAME-13', category: 'GAME', name: 'Domestic rinse ritual interaction restoring respiratory pleats' },
  { id: 'GAME-14', category: 'GAME', name: 'Bellows-Cowl survival equipment extending endurance in sulfur fog' },
  { id: 'GAME-15', category: 'GAME', name: 'Elderberry-grease protective application shielding clefts from grit' },
  { id: 'GAME-16', category: 'GAME', name: 'Hollow Wasting affliction triggered by prolonged dry Scarp exposure' },
  { id: 'GAME-17', category: 'GAME', name: 'Manna-curd nutrient consumption restoring biological silica balance' },
  { id: 'GAME-18', category: 'GAME', name: 'Audible respiratory wheezing sound effect when clefts are encrusted' },
  { id: 'GAME-19', category: 'GAME', name: 'Pleat-Leech medical clinic interaction for surgical debridement' },
  { id: 'GAME-20', category: 'GAME', name: 'Thermal regulation mechanics: lowland heatstroke vs highland hypothermia' },
  { id: 'GAME-21', category: 'GAME', name: 'Interactive Funicular operation: water bladder filling and brake release' },
  { id: 'GAME-22', category: 'GAME', name: 'Boardable Cable-Car transit system across the 2km chasm' },
  { id: 'GAME-23', category: 'GAME', name: 'Tension-Bucket hand-winch hauling for emergency crossing' },
  { id: 'GAME-24', category: 'GAME', name: 'Zip-Courier canister firing to deliver urgent message tokens' },
  { id: 'GAME-25', category: 'GAME', name: 'Emergency secondary cable clamp engagement preventing carriage drop' },
  { id: 'GAME-26', category: 'GAME', name: 'Funicular counterweight water-dumping to power lowland sluice-gates' },
  { id: 'GAME-27', category: 'GAME', name: 'Ankh-Vane turntable switching to reroute funicular car lines' },
  { id: 'GAME-28', category: 'GAME', name: 'Cable maintenance mini-game: greasing sheaves and splicing strands' },
  { id: 'GAME-29', category: 'GAME', name: 'Pendulum-sling acrobatics during Throat-Sink thermal downdrafts' },
  { id: 'GAME-30', category: 'GAME', name: 'Wind shear compensation controls during violent Scour gale gusts' },
  { id: 'GAME-31', category: 'GAME', name: 'Acoustic Resonance Tuning Fork tool to fell glass-cane at 4,200 Hz' },
  { id: 'GAME-32', category: 'GAME', name: 'Interactive Siphon valve wheels to regulate municipal water distribution' },
  { id: 'GAME-33', category: 'GAME', name: 'Hydrostatic pressure balancing to prevent water-hammer pipe bursts' },
  { id: 'GAME-34', category: 'GAME', name: 'Bile-Lye acid synthesis and application to fuse silic-timber mortises' },
  { id: 'GAME-35', category: 'GAME', name: 'Pumice-charcoal air filter crafting from harvested rift minerals' },
  { id: 'GAME-36', category: 'GAME', name: 'Water-Poaching illegal siphon tapping using flexible gut-hoses' },
  { id: 'GAME-37', category: 'GAME', name: 'Basalt chime striking to propagate long-distance acoustic telegraphs' },
  { id: 'GAME-38', category: 'GAME', name: 'Mud-sledge hauling mechanics across drained alkaline silt flats' },
  { id: 'GAME-39', category: 'GAME', name: 'Sump drainage vortex timber salvage using grapple poles' },
  { id: 'GAME-40', category: 'GAME', name: 'Scientific field sample collection of kelp, sulfur, and salt-tubers' },
  { id: 'GAME-41', category: 'GAME', name: 'Interactive Shackle Shearing event trigger on the Hanging Span of Ghrat' },
  { id: 'GAME-42', category: 'GAME', name: 'Emergency rescue escort of stranded weaving apprentices' },
  { id: 'GAME-43', category: 'GAME', name: 'Water-cart traffic management at the auxiliary Hoist #6 bottleneck' },
  { id: 'GAME-44', category: 'GAME', name: 'Hoist #6 jammed counterweight release and salt clearance task' },
  { id: 'GAME-45', category: 'GAME', name: 'Emergency grain transport bargaining with East Ledge bakers' },
  { id: 'GAME-46', category: 'GAME', name: 'Black-market water smuggling intervention or suppression choice' },
  { id: 'GAME-47', category: 'GAME', name: 'Ruptured sewer flue containment to prevent acid slurry foundation decay' },
  { id: 'GAME-48', category: 'GAME', name: 'Diplomatic dowry transport across the rift to salvage betrothal treaty' },
  { id: 'GAME-49', category: 'GAME', name: 'Sluice-wharf kelp embargo negotiation with Bailiff Kallum' },
  { id: 'GAME-50', category: 'GAME', name: 'Dual Council emergency arbitration vote to rebalance the Siphon-Compact' },

  // STAB-01 to 50
  { id: 'STAB-01', category: 'STAB', name: 'Decoupled fixed-timestep physics simulation loop running at 60Hz' },
  { id: 'STAB-02', category: 'STAB', name: 'Clamped frame delta governor preventing object tunneling' },
  { id: 'STAB-03', category: 'STAB', name: 'Memory object pool for THREE.Vector3 and Raycaster instances' },
  { id: 'STAB-04', category: 'STAB', name: 'World-space Spatial Hash Grid for entity proximity queries' },
  { id: 'STAB-05', category: 'STAB', name: 'Dynamic Level-of-Detail (LOD) geometry mesh culling' },
  { id: 'STAB-06', category: 'STAB', name: 'Unified Semantic Input Action Bus decoupling hardware devices' },
  { id: 'STAB-07', category: 'STAB', name: 'WebGL Context Loss and Restoration event listeners with auto-recovery' },
  { id: 'STAB-08', category: 'STAB', name: 'Frame-budgeted background simulation update scheduler' },
  { id: 'STAB-09', category: 'STAB', name: 'Scene hierarchy recursive disposal manager preventing VRAM leaks' },
  { id: 'STAB-10', category: 'STAB', name: 'Zero external runtime network dependencies (100% offline first)' },
  { id: 'STAB-11', category: 'STAB', name: 'Schema-versioned LocalStorage persistence engine with validation' },
  { id: 'STAB-12', category: 'STAB', name: 'Periodic background autosave every 15 seconds and on page hide' },
  { id: 'STAB-13', category: 'STAB', name: 'Complete state rehydration on page reload (time, position, stats)' },
  { id: 'STAB-14', category: 'STAB', name: 'JSON simulation state snapshot export and import functionality' },
  { id: 'STAB-15', category: 'STAB', name: 'Corrupted storage auto-recovery with fallback to baseline defaults' },
  { id: 'STAB-16', category: 'STAB', name: 'Single-click factory state reset to historical baseline' },
  { id: 'STAB-17', category: 'STAB', name: 'Real-time World State delta recorder tracking pre/post entities' },
  { id: 'STAB-18', category: 'STAB', name: 'Unsaved change detection guarding against accidental tab closure' },
  { id: 'STAB-19', category: 'STAB', name: 'Storage quota usage telemetry and warning limits' },
  { id: 'STAB-20', category: 'STAB', name: 'Session timer tracking elapsed playtime with pause-on-blur' },
  { id: 'STAB-21', category: 'STAB', name: 'Web Audio API procedural sound synthesizer for environmental winds' },
  { id: 'STAB-22', category: 'STAB', name: 'Dynamic acoustic lowpass filter tied to rising Plenum fog density' },
  { id: 'STAB-23', category: 'STAB', name: 'Resonant basalt gong synthesizer using physical modal harmonics' },
  { id: 'STAB-24', category: 'STAB', name: 'Hydrostatic fluid hiss sound generator modulated by valve flow' },
  { id: 'STAB-25', category: 'STAB', name: 'Spatialized 3D audio listener positioned on player camera' },
  { id: 'STAB-26', category: 'STAB', name: 'Dedicated gain buses for Master, Ambience, SFX, and UI channels' },
  { id: 'STAB-27', category: 'STAB', name: 'Automatic audio context suspension when tab is backgrounded' },
  { id: 'STAB-28', category: 'STAB', name: 'Zero-latency synthesized footstep sound generator' },
  { id: 'STAB-29', category: 'STAB', name: 'Cable tension mechanical whine pitch-shifted by strain loads' },
  { id: 'STAB-30', category: 'STAB', name: 'Emergency warning klaxon synthesizer with frequency sweep' },
  { id: 'STAB-31', category: 'STAB', name: 'Catenary curve mathematical formula solver for suspension cables' },
  { id: 'STAB-32', category: 'STAB', name: 'Bernoulli hydraulic fluid flow model calculating pipe pressures' },
  { id: 'STAB-33', category: 'STAB', name: 'Deterministic seeded pseudo-random number generator (PRNG)' },
  { id: 'STAB-34', category: 'STAB', name: 'Capsule and bounding-box player terrain collision detection' },
  { id: 'STAB-35', category: 'STAB', name: 'Raycast ground surface snapping with slope normal orientation' },
  { id: 'STAB-36', category: 'STAB', name: 'Numerical safety guards against NaN and Infinity in physics vectors' },
  { id: 'STAB-37', category: 'STAB', name: 'Moving platform momentum transfer on funicular cars' },
  { id: 'STAB-38', category: 'STAB', name: 'Inertia and friction coefficient physics for mud and basalt' },
  { id: 'STAB-39', category: 'STAB', name: 'Spring-damper camera smoothing with zero frame-rate hitching' },
  { id: 'STAB-40', category: 'STAB', name: 'Safe division guards across all economic supply/demand equations' },
  { id: 'STAB-41', category: 'STAB', name: 'Automated Python verification suite (verify_improvements.py)' },
  { id: 'STAB-42', category: 'STAB', name: 'Complete 200 improvement ID code-level contract enforcement' },
  { id: 'STAB-43', category: 'STAB', name: 'Runtime performance spike detector logging frame hitches >33ms' },
  { id: 'STAB-44', category: 'STAB', name: 'Headless simulation cycle test advancing 32 hours mathematically' },
  { id: 'STAB-45', category: 'STAB', name: 'Static syntax validation and lint compliance check' },
  { id: 'STAB-46', category: 'STAB', name: 'Zero uncaught console error invariant enforcement' },
  { id: 'STAB-47', category: 'STAB', name: 'Memory stress test ensuring stability over 1,000 game cycles' },
  { id: 'STAB-48', category: 'STAB', name: 'Cross-viewport CSS responsive boundary verification test' },
  { id: 'STAB-49', category: 'STAB', name: 'Zero-dependency local HTTP development server (tools/serve.py)' },
  { id: 'STAB-50', category: 'STAB', name: 'Automated World State Ledger mathematical audit verification' },

  // SIMU-01 to 50
  { id: 'SIMU-01', category: 'SIMU', name: 'Continuous 32-hour subterranean brine ocean thermal hydraulic cycle' },
  { id: 'SIMU-02', category: 'SIMU', name: 'Physically rising volumetric brine plane (0m to 60m) during Inrush' },
  { id: 'SIMU-03', category: 'SIMU', name: 'Volumetric Plenum mist ascent climbing to precisely 700m contour' },
  { id: 'SIMU-04', category: 'SIMU', name: 'Thermal diurnal inversion: 42°C hot lowland mist vs -8°C Scarp winds' },
  { id: 'SIMU-05', category: 'SIMU', name: 'The Scour wind simulation: violent upward air displacement on Scarp' },
  { id: 'SIMU-06', category: 'SIMU', name: 'The Throat-Sink wind simulation: cascading freezing downdrafts on Ebb' },
  { id: 'SIMU-07', category: 'SIMU', name: 'Crystalline silica frost precipitation on mudflats during late Ebb' },
  { id: 'SIMU-08', category: 'SIMU', name: 'Active geothermal karst vent smoke plumes with aerodynamic lift' },
  { id: 'SIMU-09', category: 'SIMU', name: 'Dynamic sun and chthonic steam illumination casting canyon shadows' },
  { id: 'SIMU-10', category: 'SIMU', name: 'Acoustic air density modulation affecting gong sound travel speed' },
  { id: 'SIMU-11', category: 'SIMU', name: '20 autonomous inhabitants executing distinct 32-hour state schedules' },
  { id: 'SIMU-12', category: 'SIMU', name: 'High Warden Vaelen Keth: cistern auditing and valve enforcement' },
  { id: 'SIMU-13', category: 'SIMU', name: 'Bailiff Kallum: commanding Sluice-Wharf Nine and funicular loading' },
  { id: 'SIMU-14', category: 'SIMU', name: 'Master Cable-Tender Barek: patrolling suspended catenary lines' },
  { id: 'SIMU-15', category: 'SIMU', name: 'Sister Morwen: performing sacred hydrological rites at Three Spires' },
  { id: 'SIMU-16', category: 'SIMU', name: 'Doctor Elyse: administering pleat debridement at Seventh Ledge hospital' },
  { id: 'SIMU-17', category: 'SIMU', name: 'Old Caelen (The Stone-Judge): presiding over Bourse disputes' },
  { id: 'SIMU-18', category: 'SIMU', name: 'Sola the Courier: executing high-speed zipline dispatch runs' },
  { id: 'SIMU-19', category: 'SIMU', name: 'Mire-Mother Thura: supervising salt-tuber farming teams' },
  { id: 'SIMU-20', category: 'SIMU', name: 'Teth the Hauler: dragging kelp sledges and coughing silica dust' },
  { id: 'SIMU-21', category: 'SIMU', name: 'Talia the Scribe: auditing clandestine water discrepancy logs' },
  { id: 'SIMU-22', category: 'SIMU', name: 'Jarek the Drum-Driver: operating Ankh-Vane funicular brakes' },
  { id: 'SIMU-23', category: 'SIMU', name: 'Nesta the Shackle-Breaker: organizing debtor resistance underground' },
  { id: 'SIMU-24', category: 'SIMU', name: 'Garrick the Broker: manipulating future water-delivery chits' },
  { id: 'SIMU-25', category: 'SIMU', name: 'Bran the Diver: scuba salvage diving in drowned ancient aqueducts' },
  { id: 'SIMU-26', category: 'SIMU', name: 'Master Dun: acoustically tuning municipal basalt signaling bells' },
  { id: 'SIMU-27', category: 'SIMU', name: 'Drusilla: breeding Pellicle-Slugs in warm Median shelf grottos' },
  { id: 'SIMU-28', category: 'SIMU', name: 'Apprentice Kaelen: balancing on slick cables under Bareks supervision' },
  { id: 'SIMU-29', category: 'SIMU', name: 'Sari: running The Snapped Cable tavern with dynamic clientele' },
  { id: 'SIMU-30', category: 'SIMU', name: 'Varek: tapping high-pressure conduits to sell bootleg rinse-water' },
  { id: 'SIMU-31', category: 'SIMU', name: 'Deterministic commodity pricing model for 6 core trade commodities' },
  { id: 'SIMU-32', category: 'SIMU', name: 'Certified water scrip (Lek) value floating based on cistern reserves' },
  { id: 'SIMU-33', category: 'SIMU', name: 'Black-Kelp flour price elasticity responding to harvest funicular delays' },
  { id: 'SIMU-34', category: 'SIMU', name: 'Manna-Curd market valuation tied to silica dietary requirements' },
  { id: 'SIMU-35', category: 'SIMU', name: 'Silic-timber pin supply reacting to acoustic logging operations' },
  { id: 'SIMU-36', category: 'SIMU', name: 'Altitude transport tariffs automatically added to cross-chasm goods' },
  { id: 'SIMU-37', category: 'SIMU', name: 'Municipal water debt ledger applying physical valve chokes to debtors' },
  { id: 'SIMU-38', category: 'SIMU', name: 'Merchant hoarding simulation during impending low-water crises' },
  { id: 'SIMU-39', category: 'SIMU', name: 'Black-market price arbitrage when municipal conduits are restricted' },
  { id: 'SIMU-40', category: 'SIMU', name: 'Reciprocal balance-of-trade index between Scarp and Gut factions' },
  { id: 'SIMU-41', category: 'SIMU', name: 'Three radical altitude environments rendered concurrently in one scene' },
  { id: 'SIMU-42', category: 'SIMU', name: 'Glacis of Keth: 1,400m plateau, Three Spires cistern, howling windmills' },
  { id: 'SIMU-43', category: 'SIMU', name: 'Strake of Tal-Mor: 710m median shelf, hanging vats, Siphon-Bourse' },
  { id: 'SIMU-44', category: 'SIMU', name: 'Sluice-Wharf Nine: 50m gut, boiling cauldrons, submerged piers' },
  { id: 'SIMU-45', category: 'SIMU', name: 'Vitreous Reach: 80m crystalline glass-bamboo forest chime physics' },
  { id: 'SIMU-46', category: 'SIMU', name: 'Weeping Basalt: natural freshwater seepage wall with public ladles' },
  { id: 'SIMU-47', category: 'SIMU', name: 'Monoliths of the Deaf Choir: acoustic stone organ pipes roaring in wind' },
  { id: 'SIMU-48', category: 'SIMU', name: 'Spire-Hub of Ankh-Vane: central pylon turntable cross-canyon hub' },
  { id: 'SIMU-49', category: 'SIMU', name: 'Drowned Aqueducts of the Great Sump: ancient cyclopean submerged ruins' },
  { id: 'SIMU-50', category: 'SIMU', name: 'Comprehensive World State Ledger audit matching Section 8 baseline' }
];

export const INITIAL_STATE = {
  timeHours: 2.0,
  timeSpeed: 1.0,
  isPaused: false,
  disruptionTriggered: false,
  disruptionHour: null,
  player: {
    x: 0,
    y: 710,
    z: 120,
    altitudeZone: 'Shelf',
    stamina: 100,
    hydrationHours: 8.5,
    vitrificationPct: 18.0,
    hasMudStilts: false,
    hasBellowsCowl: false,
    waterScripLek: 24.5,
    inventory: [
      { id: 'flank_rake', name: 'Bone Flank-Rake', count: 1 },
      { id: 'ampoule_100ml', name: 'Certified Mountain Water (100ml)', count: 3 },
      { id: 'elderberry_grease', name: 'Elderberry Grease Horn', count: 1 }
    ]
  },
  infrastructure: {
    ghratBridge: { state: 'intact', cantDeg: 0, unstrandedPct: 0 },
    hoistSix: { state: 'operational', loadPct: 45, carY: 700 },
    sewerFlue12B: { state: 'nominal', floodedLiters: 0 },
    greatCistern: { state: 'nominal', liters: 1200000, outflowLps: 100 }
  },
  market: {
    waterLek: 1.12,
    kelpFlour: 3.20,
    mannaCurd: 0.80,
    silicPins: 0.45,
    vinegarLye: 1.50,
    saltBeef: 5.00
  },
  weather: {
    windSpeedMps: 12.0,
    windName: 'The Scour Updraft',
    fogDensity: 0.42,
    ambientTempC: 22.0
  }
};
